### ISSUE TITLE
The output values of the Hψ model are all NaNs

### ISSUE THREAD

**Issue by bojinxin** [DatrikIntelligence/D3A-TS-Denoising-Driven-Data-Augmentation-in-Time-Series#1]
Dear Author,

I am very interested in your work. However, while attempting to reproduce your code and retrain the diffusion model, I encountered an issue where the data augmentation samples could not be generated. Specifically, the output values of the Hψ model are all NaNs, which suggests there might be a problem with the gradients. Could you please advise on how I might resolve this issue?

Thank you.
![Figure_1](https://github.com/user-attachments/assets/dd35a527-1ba7-434e-b651-ffdfba7d0d32)
![pred_noise](https://github.com/user-attachments/assets/d87b4ae3-896e-4489-b91b-6d9a7fa8e99c)

**Comment by dasolma** [comment]
Hello @bojinxin ,

Thank you for your interest in our work. 

Are you normalizing the data? In my experience, this happens when the input values have a wide range.
